hxrsnd/pneumatic.py, hxrsnd/sndsystem.py, hxrsnd/tests/test_pneumatic.py, hxrsnd/tests/test_sndsystem.py
Overview
------------
PR adds classes to control the pneumatic devices of the system. This includes the proportional valves and pressure switches on towers 1 and 4, in addition to the system level valve and switch. The classes that map to these two devices are in `pneumatic.py` and are `ProportionalValve` and `PressureSwitch` respectively. I initially wanted to split off the components to each of the towers and then the last pair at the `SplitAndDelay` level, but as per Diling's request, I organized the vacuum components into their own high-level device called `SndVacuum`. There were also some changes made to better organize the methods of the high-level classes in `sndsytem.py`. Tests were written for all the new classes.
Pneumatic Classes
------------
`PneuBase` - Base class for the …
=> ENH: Adding classes for pneumatics

hxrsnd/aerotech.py, hxrsnd/attocube.py, hxrsnd/bragg.py, hxrsnd/pneumatic.py, hxrsnd/sndsystem.py, hxrsnd/tests/test_epics_aerotech.py, hxrsnd/tests/test_epics_attocube.py, hxrsnd/tests/test_utils.py
Overview
-------------
This PR corrects the high-level motion methods so that the equations are correct and also adds in waiting and status checking. Low-level motor classes were given the ability to optionally check their status, so that the checks can be done all at once in the higher-level methods. The energy methods also now move the diagnostic motors as well to the expected positions. Aliases were added for all the energy methods for convenience.
Equations/Conversions
--------------------------------
Yanwen provided a new set of equations to use which was picked apart and moved into a few different functions:
`delay_to_length`
- Calculates the length of the delay stage necessary to achieve the inputted delay. Essentially converts from delay time (ps) to motor position (mm) but can be …
=> ENH: Fixed the energy and delay calculations and made them better to use.

hxrsnd/aerotech.py, hxrsnd/attocube.py, hxrsnd/tests/test_epics_aerotech.py, hxrsnd/tests/test_epics_attocube.py
Overview
-------------
Diling was complaining about status objects being returned everywhere so I made it optional for all methods that previously returned them. I have also made it so that the only methods that return a status object by default are the `move` and `rel_move` methods. *All other methods now no longer return status objects by default, this includes the aliases for `move` and `rel_move`.* Also, `EccBase` was missing a `set_limits` method, so I added it.
Returning Status Objects
---------------------------------
All methods that previously returned a status object now have two additional arguments:
- `ret_status` - Bool that determines if a status object should be returned
- `print_set` / `print_move` - Bool that determines if a short message should be printed to the console …
=> ENH: Optionally return status objects for motors. Log or print everything.

hxrsnd/aerotech.py, hxrsnd/attocube.py, hxrsnd/bragg.py, hxrsnd/detectors.py, hxrsnd/diode.py, hxrsnd/exceptions.py, hxrsnd/plans.py, hxrsnd/pneumatic.py, hxrsnd/rtd.py, hxrsnd/sndsystem.py, hxrsnd/state.py, hxrsnd/tests/test_aerotech.py, hxrsnd/tower.py, hxrsnd/utils.py
Overview
-------------
PR to try and a couple more items on Diling's controls list. The following issues are addressed:
- Pressure checks before motions of `tth`, `x` and `L` motors.
- New aerotech classes were made - `InterLinearAero` and `InterRotationAero` that have an extra component for the pressure switch and check in the `check_status` method.
- Energy and delay combined motion
- Redid the energy and delay setting routine. There is now one pipeline that handles setting all the energies and delay with aliases that pass different arguments.
- Nicer handling of failures
- At the motor level, whenever `mv` or `mvr` are used, they will catch motor errors and display them nicely. This still needs to be implemented at the higher level classes.
- `status()` prints are greatly reduced
- …
=> ENH: Addressing a bunch of Diling's requests

bin/run_snd, bin/run_snd.py, docs/source/running_the_daq.rst, hxrsnd/aerotech.py, hxrsnd/attocube.py, hxrsnd/diode.py, hxrsnd/macromotor.py, hxrsnd/plans.py, hxrsnd/pneumatic.py, hxrsnd/sndsystem.py, hxrsnd/tower.py, hxrsnd/utils.py
Overview
=======
This PR adds the ability to scan using the DAQ by introducing a basic `linear_scan` plan and a runengine that is preconfigured to interface with the DAQ. There is also a document on how to properly run scans with the DAQ. Tab completion is now much faster since all objects are no longer instantiated lazily. When a macro move is made, you can now specify whether you want to move the diagnostic motors as well. Additional `exports` are included in the launcher script that should make it usable from `xcs_daq` and beyond.
=> ENH: Adding daq scans, fixed slow tab completion, optional diagnostic macro moves

hxrsnd/attocube.py, hxrsnd/diode.py, hxrsnd/macromotor.py, hxrsnd/plans.py
Overview
=======
Adding a fix to allow all motors to be passed to the scan. Quick additions elsewhere - changing component to be the default version from `ophyd`.
=> FIX: Allowing the scans to be used with all motors.

.travis.yml, hxrsnd/aerotech.py, hxrsnd/attocube.py, hxrsnd/detectors.py, hxrsnd/diode.py, hxrsnd/macromotor.py, hxrsnd/plans.py, hxrsnd/pneumatic.py, hxrsnd/rtd.py, hxrsnd/sndsystem.py, hxrsnd/tests/conftest.py, hxrsnd/tests/test_aerotech.py, hxrsnd/tests/test_attocube.py, hxrsnd/tests/test_detectors.py, hxrsnd/tests/test_diode.py, hxrsnd/tests/test_macromotor.py, hxrsnd/tests/test_plans.py, hxrsnd/tests/test_pneumatic.py, hxrsnd/tests/test_rtd.py, hxrsnd/tests/test_sndsystem.py, hxrsnd/tests/test_states.py, hxrsnd/tests/test_tower.py, hxrsnd/tower.py, requirements.txt
Overview
------------
This PR makes all the necessary changes to to use 1.0.0 versions of `ophyd` and `bluesky`. Most of the changes were:
- All `ophyd` devices needed to have name as part of the `__init__`
- `bluesky` imports needed to be redone since they broke up `plans.py`
- Creating simulated devices using `using_fake_epics_pv` wrapped around a function for declaring the devices
-  Slight changes were needed to get `test_plans.py` to work since `Reader` and `Mover` have been deprecated
=> Upgrading the HXRSnD to ophyd and bluesky 1.0.0

hxrsnd/macromotor.py, hxrsnd/tests/test_macromotor.py
Do not merge until tested, but here's my outline for rolling a generalized calibration config into the parent `MacroMotor` class.
The summary is:
- Pass any combination of motor names and calibration data to the `configure` method
- On `set(pos, use_calib=True)`, pull from the saved data, interpolating if necessary. (Do not attempt to interpolate beyond edge values)
Note that this requires ophyd >= 0.8.0 for `AndStatus`
=> ENH: First pass at generalized calibration configuration

bin/run_snd.py, hxrsnd/sndsystem.py
Overview
-------------
Adding the daq back to the split and delay class since it was removed and travis doesn't run the test for it unless it is in the same subnet.
=> FIX: Adding daq back to SplitAndDelay class.

bin/run_snd
Overview
-------------
This PR changes conda environment used to be the central pcds-0.2.0 env rather than the rhel6 one.
=> ENH: Changing conda environment to use pcds-0.2.0

hxrsnd/aerotech.py, hxrsnd/attocube.py, hxrsnd/bragg.py, hxrsnd/detectors.py, hxrsnd/diode.py, hxrsnd/exceptions.py, hxrsnd/macromotor.py, hxrsnd/plans.py, hxrsnd/pneumatic.py, hxrsnd/rtd.py, hxrsnd/sndsystem.py, hxrsnd/state.py, hxrsnd/utils.py
This adds a new component to the aerotech motors for handling the state, simply called `state`. There is now a new method called `ready_motor` that will clear, enable and change the motor state to go. There were also some bug fixes to the way these "set methods" were handling status objects. 
There was no way to control the state pv previously. Also makes it easier to ensure the motor is ready for use.
Simply using the old tests. New tests will be written in the future.
=> ENH: Added state as a component for aerotech motors

hxrsnd/sndsystem.py
The diodes were all reversed in the direction they moved in the block method.
=> FIX Reversing the directions of the blocking methods.

hxrsnd/aerotech.py, hxrsnd/attocube.py, hxrsnd/sndsystem.py, hxrsnd/tower.py, screens/motor_expert_screens.sh
There are PV name changes in the newest attocube IOC that come with aliases which are nicer to work with. This PR simply makes the changes necessary to use the aliases.
We have been running the `1.0.1` release of the attocube IOC when the most recent release is now `1.0.6`. This was necessary to actually use it.
Passes all the existing tests.
=> MAINT: Updating Attocube motor names to use PV aliases

conda-recipe/meta.yaml, hxrsnd/__init__.py, hxrsnd/macromotor.py, hxrsnd/tests/conftest.py, hxrsnd/tests/test_aerotech.py, hxrsnd/tests/test_attocube.py, hxrsnd/tests/test_diode.py, hxrsnd/tests/test_macromotor.py, hxrsnd/tests/test_pneumatic.py, hxrsnd/tests/test_rtd.py, hxrsnd/tests/test_scripts.py, hxrsnd/tests/test_sequencer.py, hxrsnd/tests/test_snd_devices.py, hxrsnd/tests/test_snddevice.py, hxrsnd/tests/test_sndmotor.py, hxrsnd/tests/test_sndsystem.py, hxrsnd/tests/test_tower.py
- `using_fake_epics_pv` is harder to use and `make_fake_device` is available
- some hotfixing on top of 1.2.0, I'm making PRs. If there is a new release in time we'll just remove the hotfixes and use that
- stricter rules about "well-formed" devices
I had to give up on a few tests, maybe I'll try again after my vacation.
- Trying to step toward upgrading our environment to the newest ophyd
=> TST: Upgrade to ophyd=1.2.0

hxrsnd/macromotor.py
Bug I missed in my crusade to ophyd=1.2.0. The sndsystem fails to load because XCS:SND<opalPV> doesn't exist.
=> FIX: don't add the prefix on this PV

hxrsnd/aerotech.py, hxrsnd/attocube.py, hxrsnd/plans/scans.py, hxrsnd/pneumatic.py, hxrsnd/tests/test_aerotech.py, hxrsnd/tests/test_attocube.py
`Signal.value` was deprecated in a recent version of ophyd, with a very verbose error message indicating why it happened and why you shouldn't be using it. 
This PR removes `.value` attribute access and replaces it with `.get()`.
Related to "verbosity" issue in #99 
Tests are still passing locally.
=> FIX: ophyd signal .value deprecation -> .get()

hxrsnd/aerotech.py, hxrsnd/attocube.py, hxrsnd/macromotor.py
Closes #107 
Going to check attocube ones before proceeding with the merge.
* The updated move interface was not compatible with the custom code present in hxrsnd.
* Tested with a simulation IOC and the split and delay device (https://github.com/pcdshub/sim-ioc/pull/3)
* `umv` and `umvr` work without issue:
```
In [2]: snd.t1.th1.enable()
In [3]: snd.t1.th1.umvr(1)
snd_t1_th1: (1.0000) [Complete.]
```
=> FIX: aerotech mvinterface incompatibility

conda-recipe/meta.yaml, hxrsnd/tests/test_tower.py
As a consequence of pcdsdevices v4.0.0, the api used in these tests is no longer valid.
No functional changes to the library code.
=> TST: update tests, update dep tag to match

hxrsnd/tests/test_plans_calibration.py
Ref https://github.com/pcdshub/pcds-envs/pull/199
This fixes a test failure with the latest bluesky, where a test fixture changed underneath us.
pcds-4.2.0 had a bluesky with a non-parametrized `RE` (which we import as `fresh_RE`) which passed just fine.  I reproduced the failure locally with just the latest bluesky and hxrsnd in pcds-4.2.0. Turns out it's simply because we're running the same test twice, re-using motors at different starting positions.
Test suite.
=> TST: detector_scaling_walk_start_positions_are_valid with latest bluesky

.travis.yml
Use the latest-only (3.9-only) branch of the shared CI configs
Update the allow failures
Anaconda upload did not run on the last tag because the 3.7/3.8 builds fail because pcdsdevices dependency
Did not get caught at PR because the PR did not run the travis somehow
=> CI: use only latest, only latest will pass

conda-recipe/meta.yaml, hxrsnd/macromotor.py
Make the macromotor readbacks hinted
Did not show up in the BEC LiveTable
https://jira.slac.stanford.edu/browse/LCLSECSD-1098
It has not been tested
It has not been documented
=> BUG: fix issue where macro motor readback was not hinted

conda-recipe/meta.yaml
Quickly resolve some incompatibilities when the conda solver decides it wants to give us old versions
Conda uploads are failing because pcdsutils v0.4.0 is being installed
=> BLD: update pins

hxrsnd/tests/conftest.py
A few tests here fail when run offline. I'm not sure why they pass on travis CI.
There are some really old "make the thing behave different in the test" instances that inevitably break over time.
I'm not really interested in finding a full better way to do these today- I just want to patch over it and move on.
=> TST: fix issue with outdated test hotfix

.pre-commit-config.yaml
Gitlab -> github
Gitlab mirror is gone/private
I wanted to build/upload to pcds-tag but this breaks the CI
=> MAINT: switch to original instead of down mirror

hxrsnd/macromotor.py, hxrsnd/sndsystem.py
For many years now, xcs3 has had a dev checkout hotfix for `hxrsnd` that adds a pseudopositioner that calculates the delay for the split and delay.
I added this here as-is with no changes.
As part of https://jira.slac.stanford.edu/browse/ECS-6333 I'm wrangling dev hotfixes into tags.
This hotfix has been active forever, is innocuous, and doesn't interfere with anything else in the module.
Interactively at xcs since forever ago
This PR only (later, release notes)
=> ENH: add xcs3 hotfix (delay pseudo)
